---
printWidth: 120
tabWidth: 2
useTabs: false
endOfLine: crlf
semi: false
singleQuote: true
quoteProps: as-needed
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: true
